### ISSUE TITLE
ks_nordschleife is missing layout options

### ISSUE THREAD

**Issue by karlisk4** [cj123/assetto-server-manager#123]
Provided a screenshot, could be due to the wierd structure Nordschleife is built.

**Comment by karlisk4** [comment]
Github Won't let me upload screenshots without reason, I guess thats a bug

**Comment by cj123** [comment]
hi! 

Unfortunately by default the assetto corsa server does not install all the track layouts. This confuses me, but that's the case.

To add the missing layouts, just re-upload the track from your local assetto corsa install on the tracks page. 

If you do this for all your tracks, you'll get nice preview images and such too!

Hope this helps :)
