### ISSUE TITLE
reversed race positions (+ extra race) do not work with championships?

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#130]
The option "-1" (inverted grid) but it never worked.

We did 2 tests ... the two failed

**Comment by cj123** [comment]
Hi!

I was actually discussing this with @CaptainCondescending this week. We've never done a race using that option in Assetto Corsa, and I forgot to test it!

I'll definitely be looking into supporting this option (both in Custom Races and Championships) when I do some updates this weekend.

**Comment by luismercury** [comment]
don't work in mode  championships.
![creenshot11](https://user-images.githubusercontent.com/48275749/54073429-ba863b00-4265-11e9-87f9-1b759f235256.jpg)

**Comment by cj123** [comment]
this will be fixed in #133:

![image](https://user-images.githubusercontent.com/306873/54074191-65f3b780-4287-11e9-9b1e-e97e3998f6d0.png)
