### ISSUE TITLE
championship sign up form

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#197]
i've seen quite a few spreadsheets out there for signing up to championships. thought it might be good to have a form integrated into server manager to sign up

usual details i've seen:

* name
* team name
* car choice
* skin choice?
* maybe an email so they can be contacted? idk

**Comment by luismercury** [comment]
Steam Guid?
Add skin choice?  (for personal skin)

**Comment by cj123** [comment]
optionally require a CAPTCHA to be passed (if captcha options are set in config.yml)?
