### ISSUE TITLE
add Countdown ?

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#235]
Is it possible to add a countdown for a scheduled event?

For example :
![creenshot12](https://user-images.githubusercontent.com/48275749/55878652-38927600-5b73-11e9-8ff4-8f51f5a9484e.jpg)

thank you mate !

**Comment by cj123** [comment]
Hi Luis,

We much prefer showing the time that the event will occur rather than a countdown - I think a countdown is harder to follow especially for events months in the future!

**Comment by luismercury** [comment]
Hi Callum,

Perhaps it's understood as a replacement.
My idea is that both options coexist in the same screen.

Actually it's not an idea of ​​mine ... it's the information that I can see every day in iRacing or SRS to cite examples.
and if the idea prospers, it should have a low priority.

thks
