### ISSUE TITLE
It's possible? Move this skin display

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#244]
Excellent visualization.
![creenshot11](https://user-images.githubusercontent.com/48275749/56040745-7a572400-5d0d-11e9-92ba-cd0527217a34.jpg)

It's possible? Move this skin display here.

In our community We have 30 drivers and this visualization is under Drivers's standings

thanks

**Comment by cj123** [comment]
Hi Luis,

I much prefer the skins below the table, since the information in the table is more important than the skins, so it should go at the top.
