### ISSUE TITLE
Server Logo

### ISSUE THREAD

**Issue by Hecrer** [cj123/assetto-server-manager#260]

**Comment by WraithStar** [comment]
I would do it as a payware "premium" feature tbh if I were in you.
I'm pretty sure everyone would be ok with that, and you guys pretty much deserve it.

**Comment by cj123** [comment]
closing, this is possible with custom css.

**Comment by vitoexe** [comment]
> closing, this is possible with custom css.

@cj123  it possible but, it's hack.  
For example Facebook, not recognize this image because this is background. And links to events has pinguin logo 

Can you add for example Custom JS feature?
Or some example how to add this to custom css in proper way?
