### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by jmp0xf** [cj123/assetto-server-manager#299]
I tried to compile the executable myself to obtain the newest features and to get rid of some bugs, but it seems that these code are not intact(at least in master branch). After bypassing several "undefined" errors, the final myself-compiled program still did not work properly.

**Comment by cj123** [comment]
Hi!

First off, could you tell me a bit about how you were compiling it? 

1) What go version are you running? 
2) What steps did you take to compile it?
3) When you say "did not work properly", can you give specifics?

Thanks

**Comment by jmp0xf** [comment]
Sorry to bother, I just figured out where the issue lies. I should use go generate to generate two missing go files.
