### ISSUE TITLE
sort car list into classes?

### ISSUE THREAD

**Issue by CaptainCondescending** [cj123/assetto-server-manager#303]
Not sure how this would work but I've been thinking about it for a while. The ability to sort cars into classes (eg GT3, GTE, LMP1 etc), and then bulk import them into an event.

**Comment by cj123** [comment]
cars have a `ui_cars.json` file, which contains the following:

```
	"tags": ["#small sports", "fwd", "manual", "turbo", "street", "hot hatchback", "italy"],
```

perhaps adding the ability to search by tags might be a simple way of doing this?

**Comment by cj123** [comment]
...and right below it (i'm blind apparently) there is

```
"class": "street",
```

**Comment by cj123** [comment]
perhaps an autofill class dropdown would work here? We can enumerate all the classes and then have a dropdown that populates cars into the car list when you choose that class?

**Comment by CaptainCondescending** [comment]
would only work if there is a way to add/remove tags but otherwise yeah that's pretty much what i had in mind

**Comment by CaptainCondescending** [comment]
*car info page*

**Comment by cj123** [comment]
linking #338
