### ISSUE TITLE
Improving live timing readability

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#306]
There is a main issue currently: the players list gets squeezed vertically because of the cars' names getting word wrapped, and therefore becomes very difficult to read even on wider screens, especially when the cars' names are very long. 

Perhaps being able to choose which columns to display / hide might be a workaround? (maybe also separate car skin name and car name in different columns could be a good idea)

Here is an example of what I mean
![immagine](https://user-images.githubusercontent.com/33436040/57559130-ba4b0e80-7380-11e9-85fd-76303b4830d8.png)

**Comment by Hecrer** [comment]
We could look into hiding columns, although we are considering removing the skin name from the car entry completely as it isn't really useful in the context of the live map.

**Comment by WraithStar** [comment]
> 
> 
> We could look into hiding columns, although we are considering removing the skin name from the car entry completely as it isn't really useful in the context of the live map.

That makes sense, _telling_ the name of the skin doesn't really _tell_  anything. A full skin preview would make sense, but that would just make the whole list even more difficult to read, so yeah
