### ISSUE TITLE
"race weekend": a system to specify different sessions across different days (within championships)

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#308]

**Comment by Nordicdesign** [comment]
If I understand it correctly, is exactly what I was looking for. In our league immediately after a race we would turn the server on for the next one. That could be a week's time or two. People will start practicing on the server and want to compare between themselves, see where they are losing time, generate banter, etc. At the moment the results page shows individual sessions, but I have no way to see _all_ best times from practice for a particular track.

This is what we use for rFactor2 and works really well. Shows the best lap of each driver and then if you drill in you can view all individual laps. To be honest, only the first part is needed (overall best lap), so people know how far off are from the top guys :) 
http://hlssim.com/hotlaps/Circuito.aspx?id_track=18345&id_comunidad=15&id_campeonato=9302

**Comment by Hecrer** [comment]
This I think is more linked to #262, showing best laps with certain car/track combinations etc. Currently if you run a championship and use the looping practice session provided your best times should be stored in the live timings page, but a system like this would be a definite improvement.

**Comment by cj123** [comment]
Following some testing last night, I can confirm that EntryList positions are respected in sessions that just have a Race event. So for example an EntryList with the following:

```
[CAR_0]
DRIVERNAME=Callum

[CAR_1]
DRIVERNAME=John

[CAR_2]
DRIVERNAME=

[CAR_3]
DRIVERNAME=Joseph
```

Would correctly place the grid as follows:

1. Callum
2. John
3. <empty>
4. Joseph

This is the only Assetto Corsa feature that this ticket requires, so work can begin for this towards 1.4 when we get around to it.
