### ISSUE TITLE
Championship register form assigns cars even if they are already been taken

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#316]
Step 1: create a new championship with locked entry list, put a certain number of cars in the entry list (we put only 1 Fiat 500 and only 1 Ferrari 458 for this example in the entry list, and also can add other different random cars)

Step 2: apply for the championship. Select the Fiat 500, choose any skin you want. Approve the application.

Step 3: apply for the championship using different credentials. 

Problem 1: in the application form, you can still choose the Fiat 500, even if it has been already taken before.

Step 4: approve the second application.

Problem 2: As the application gets approved, the Server Manager will literally kick another random car from the entry list and replace it with a new Fiat 500. Also, if the kicked car was the only one available in the list (the single Ferrari 458 we added before), new applicants won't even be able to choose that one because it has already been kicked out.

**Comment by Hecrer** [comment]
Problem 1: This only occurs if admin approval is enabled, the idea is that if somebody wants to apply for a car (even if it is full) then they still can, and the admin is in charge of making decisions/contacting people etc. taking control away from users is something that we try to avoid. I do think this needs some more detailed information though. Maybe the sign up page should tell you how many people have applied/have been accepted for a car. (so in your example it would say Fiat 500 (1/1 approved).

What do you think about that solution?

Problem 2: Good spot, this is definitely a bug, we'll get right on that.
