### ISSUE TITLE
Live Map - out of bound

### ISSUE THREAD

**Issue by fahadgaffoor** [cj123/assetto-server-manager#319]
Hi, 
I have successfully installed the app.
But when it comes to live map, the player cars are out of bound and doesnt show with the map limit. 
What is the fix for this?
![out-of-bound](https://user-images.githubusercontent.com/50675885/57798116-94f24200-777e-11e9-8d82-1d880f70641b.jpg)

**Comment by cj123** [comment]
Hi!

I've seen issues like this occur when resizing the browser window after loading it. Does a refresh after resizing the window fix the issue?

**Comment by germanrcuriel** [comment]
This only happens when "rotated" class is applied. Will try yo provide a fix as I have my own implementation on top of server-manager API

**Comment by cj123** [comment]
i believe this is fixed in #404
