### ISSUE TITLE
running multiple instances of server manager while maintaining login

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#339]
this one definitely requires some investigation:

---

Now when I put them back online (other admin shut them down for rF2 race) I get the same problem I had before with the login. As soon as I log into one, the session is gone on the other. Although I've inspected the local/session storage and can't find any information about my user, so no idea how it knows I'm logged in!

And the HTTP port is different, and it's opened UDP/TCP in both cases

League server:
```
NAME=Exiled - League server
PASSWORD=--
ADMIN_PASSWORD=--
UDP_PORT=9600
TCP_PORT=9600
HTTP_PORT=8081
UDP_PLUGIN_LOCAL_PORT=53185
UDP_PLUGIN_ADDRESS=127.0.0.1:53186
```
fun server:
```
NAME=Exiled - Fun server
PASSWORD=--
ADMIN_PASSWORD=--
UDP_PORT=9601
TCP_PORT=9601
HTTP_PORT=8082
UDP_PLUGIN_LOCAL_PORT=50544
UDP_PLUGIN_ADDRESS=127.0.0.1:50545
```

**Comment by germanrcuriel** [comment]
AFAIK if the host is the same and the only thing different is the port, you could go with cookies to share the login/session. The thing I have myself is a bunch of docker containers with credentials and assetto content folder in a shared volume, but yeah, need to login in each one separately.
