### ISSUE TITLE
Entry list is limited to 18 entrants

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#343]
With 1.3.1 release, there is no need to specify the number of max players anymore in Custom Events. That's a nice thing, but apparently it's not possible to add more than 18 cars in the entry list for some reason. 

Just click on the orange button Add Entrant(s) once you added 18 cars already and nothing happens, even if the track supports more than 18 cars

**Comment by cj123** [comment]
This is definitely a bug. Thanks for bringing this up - i'll try and get it fixed soon :)

**Comment by cj123** [comment]
a workaround for this (temporarily) is to turn on a booking session, edit the number of Max Clients, and then turn off the booking session.
