### ISSUE TITLE
Working directory for run_on_start commands is the same of the manager's binary location

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#347]
Currently you really have to throw all the plugins you want to run in the AC Manager's directory if you want to use them, as that's the working directory of all the commands started by the ``run_on_start:`` feature,. 
Some plugins really don't want to run in different working directories than the one they are placed into, and putting multiple plugins in a single directory is, well, kinda bad.
Perhaps the working directory of the ``run_on_start:`` commands should be the one where the specified binary to launch is placed instead.

Mind tho, there is already a workaround:

If we create a script named ``runMyPlugin.sh`` in the AC Server Manager's directory and in the script we write: 
```sh
#!/bin/sh
cd /foo/bar/myPlugin
./myPlugin --myArgs
```
then we set run_on_start: down below like this
```yml
run_on_start:
  - ./runMyPlugin.sh
```

This will succesfully change the working directory and the plugin will run in its own directory with no issues.

**Comment by cj123** [comment]
I'll need to explore the implications of this one and do a bit of testing, but I don't foresee any major issues with it. Hopefully we'll be able to make this change for 1.3.2
