### ISSUE TITLE
24H Event/Driver switch

### ISSUE THREAD

**Issue by HendrikRoth** [cj123/assetto-server-manager#355]
Hello, can you tell me how to setup an 24h event with driver switch?

I tried to set multiple GUID's for one car, but we can still join?
How should the guids be splitted maybe?

Thank you :-)

**Comment by WraithStar** [comment]
Does Assetto Corsa even support this kind of stuff? I doubt about it....if so, this is pretty much unrelated with AC Server Manager

**Comment by Hecrer** [comment]
As far as I am aware this isn't possible at all in Assetto Corsa, so unfortunately we can't do anything to implement it.
