### ISSUE TITLE
stored times does not sort correctly

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#366]
![image](https://user-images.githubusercontent.com/306873/58763815-edd02180-8557-11e9-9712-b6487df9b1da.png)

looks like it's still doing a string comparison?

**Comment by WraithStar** [comment]
From what I've seen, I'd say it has to do with the truncated time strings...just don't truncate the time everytime you find a zero. Makes the times more clear, too.

Just this I guess ``1m36.53s`` -> ``1m36.530s``

Blank times do mess up the sorting too, though. Still haven't figured out how.

**Comment by cj123** [comment]
so the 1m36.53 here is actually a 1m36.053s, so the sorting is correct, the text display is wrong! fix incoming.
