### ISSUE TITLE
Find a solution for acServer not producing server log files

### ISSUE THREAD

**Issue by WraithStar** [cj123/assetto-server-manager#394]
Kunos had the genius idea to have Assetto Corsa not producing log files by itself, they went for the lazy way and bundled this batch file to launch the server executable with. This is the only way we can get server log files (on Windows).

```cmd
@echo off
TITLE AC Server
echo Starting AC Server...
SETLOCAL EnableDelayedExpansion
 for /f "skip=1 tokens=1-6 delims= " %%a in ('wmic path Win32_LocalTime Get Day^,Hour^,Minute^,Month^,Second^,Year /format:table') do (
        IF NOT "%%~f"=="" (
            set /a _d=10000 * %%f + 100 * %%d + %%a
			set /a _t=10000 * %%b + 100 * %%c + %%e
        )
    )

echo Output is logs/session/output%_d%_%_t%.log

acserver.exe > logs/session/output%_d%_%_t%.log 2> logs/error/error%_d%_%_t%.log
```
The problem is pretty evident: with acServer not producing log files by itself, we have to tell Server Manager to write these files in some way, if we want them

**Comment by Hecrer** [comment]
Options are:

- Just run the .bat file when launching the server (does it close properly? Needs testing)
- Write something that writes the logs to a file in server manager as well as writing to the web interface

**Comment by WraithStar** [comment]
Workaround (thanks @cj123 for the idea) - tested and working on both Windows and Linux

- for Linux: have the acmanager run this sh script instead of acServer binary

```sh
#!/bin/bash
LOGFILE=`date "+%Y-%m-%d_%H.%M.%S.log"`
./acserver >$LOGFILE
```

- for Windows: have the acmanager run this bat file instead of acServer binary

```cmd
@echo off
TITLE AC Server
echo Starting AC Server...
SETLOCAL EnableDelayedExpansion
 for /f "skip=1 tokens=1-6 delims= " %%a in ('wmic path Win32_LocalTime Get Day^,Hour^,Minute^,Month^,Second^,Year /format:table') do (
        IF NOT "%%~f"=="" (
            set /a _d=10000 * %%f + 100 * %%d + %%a
			set /a _t=10000 * %%b + 100 * %%c + %%e
        )
    )

echo Output is logs/%_d%_%_t%_server01.log

acServer.exe > logs/%_d%_%_t%_session_server01.log 2> logs/%_d%_%_t%_error_server01.log
```

**Comment by cj123** [comment]
Closing this ticket via the [new wiki entry on ACServer Logging to File](https://github.com/cj123/assetto-server-manager/wiki/ACServer-Logging-to-File). Thanks to @WraithStar for the testing here :)
