### ISSUE TITLE
ac server wrapper message for championships

### ISSUE THREAD

**Issue by CaptainCondescending** [cj123/assetto-server-manager#413]
A way of setting the AC server wrapper message in the championship setup, so you can link the championship page or whatever - so I don';t have to keep asking @cj123 to do it

**Comment by cj123** [comment]
will require an implementation of the ac-server-wrapper protocol inside server manager, which is something that I want to do but haven't yet understood ac-server-wrapper enough to do so

**Comment by cj123** [comment]
closed in #433
