### ISSUE TITLE
No time for Custom Race (issue)

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#416]
It's necessary to go to "laps" and then return to "time" so that the field appears

![image](https://user-images.githubusercontent.com/48275749/60931431-f838b600-a28f-11e9-98e0-0e1df3525c91.png)
![image](https://user-images.githubusercontent.com/48275749/60931547-4352c900-a290-11e9-8e37-37d6d59c5912.png)
![image](https://user-images.githubusercontent.com/48275749/60931582-65e4e200-a290-11e9-8925-c61ddc9f1c33.png)

**Comment by cj123** [comment]
Hi Luis, what browser are you using?

**Comment by luismercury** [comment]
![image](https://user-images.githubusercontent.com/48275749/60975902-14296f80-a303-11e9-9a1f-8026ea2e9f4a.png)

**Comment by cj123** [comment]
I found this issue while working on a different feature. will try and back port it into v1.4
