### ISSUE TITLE
improve/clarify sol session start time in multiple timezones

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#421]
i think sol start time doesn't need to worry about timezones at all in displaying to the user?

>When choosing a time for SOL weather, it says "Asia/Shanghai" but it's actually circuit's local time. So I want this "(Asia/Shanghai)" to be removed.
Also, when pressing SAVE to save the custom race and edit again, the time will become the time + 8 hours, which is 21:00 so every time we want to edit again even only change the circuit we use, we should always set the time again which is kind of annoying.

![image](https://user-images.githubusercontent.com/306873/61042890-faecf580-a3cc-11e9-83aa-9c33ad7b90ae.png)

https://www.racedepartment.com/threads/ac-server-manager.165662/page-15#post-3006235

**Comment by Hecrer** [comment]
Also fix editing the event adding eight hours to the start time, bloody timezones.

**Comment by Hecrer** [comment]
Also server welcome message is apparently:

"This server is running Sol with a 0 time progression multiplier" when the setting is actually 1. Probably related, definitely close by.
