### ISSUE TITLE
Tool that kicks who has sol or mandatory apps inactive

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#425]
As a option....

Eg. Sol
Eg Helicorsa
Eg: pTracker
Eg: Crew Chief

**Comment by dadebolo** [comment]
> As a option....
> 
> Eg. Sol
> Eg Helicorsa
> Eg: pTracker
> Eg: Crew Chief

Hi!
For Sol and a private app I made it self. 
Sol inactive? Kikc!
App inactive? Kick!

But Sol and all others apps run only on the client, a check on the server is not possible without a connection/interaction with the client.

**Comment by cj123** [comment]
I don't think that this is technically possible without a client side app, and so that makes it kinda useless - if people are willing to install the client side app, why wouldn't they have the recommended apps installed too?
