### ISSUE TITLE
Would be possible a weather API?

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#448]
Would it be possible to make Sol weather update based on reality? (Using some kind of weather API eg: https://openweathermap.org). ?

https://openweathermap.org/api

**Comment by cj123** [comment]
now possible via the lua plugins - check out: [plugins/events.lua](https://github.com/cj123/assetto-server-manager/blob/master/cmd/server-manager/plugins/events.lua), specifically: "weatherAPI"
