### ISSUE TITLE
LockedEntryList vs PickupMode

### ISSUE THREAD

**Issue by dadebolo** [cj123/assetto-server-manager#477]
Hello,
I know that this theme has been edited und changed many times.
This is my personal experience with all sessions that work always perfect (whether single races  or championschip events):

1 no booking / locked entry list --> pickup_mode = 1, locked_entry_list = 1 
2 no booking / no locked entry list --> pickup_mode = 1, locked_entry_list = 0
3 booking / locked entry list --> no possible!
4 booking / no locked entry list --> pickup_mode = 0, locked_entry_list = 0

NOTE: in case 1 rejoin is not necessary if Loop Mode ON!

I hade rebuilt the Server Manager 1.4.1 for me and as written everything works super perfect now!
If you need there are in attachment the objects of version 1.4.1 that I have editet.

[Edit.zip](https://github.com/cj123/assetto-server-manager/files/3522207/Edit.zip)

**Comment by cj123** [comment]
I'm at a bit of a loss with this. We've had so much back and forth with locked entry list and pickup mode.

I'm generally inclined to agree with what I see here, but we have other tickets claiming that locked entry list isn't a thing anymore.

I think we need to verify this fully and then form an unchanging stance (barring any new information) on how we deal with entry list locking.

I would say 'just let the user control it all the time' but then features of server manager (e.g. open championships) just won't work properly.

Referencing all the issues I can find about this:

#271 
#331 
#296

**Comment by cj123** [comment]
fixed in 1.4.2... hopefully.
