### ISSUE TITLE
Race result ignored.

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#485]
There are races that don't generate the results.
![image](https://user-images.githubusercontent.com/48275749/63619158-3ed63b80-c5c4-11e9-9feb-c930749d1f81.png)

There are races that don't generate the results.
Then I use the same settings and everything seems to be ok.

http://clubcsr.ddns.net:8780/results

BTW, in CM everything seems to be all ok.
![image](https://user-images.githubusercontent.com/48275749/63619206-5dd4cd80-c5c4-11e9-8b4e-0f89e6275ef2.png)

Are there possibilities to import and reconstruct the results from these jsons?

CM
![image](https://user-images.githubusercontent.com/48275749/63619247-78a74200-c5c4-11e9-9a6b-e79fc66ff748.png)

**Comment by cj123** [comment]
Results files aren't written by the acServer executable if you stop if early. You must wait until the wait time has completed before you stop the assetto corsa server. There is nothing we can do to prevent this - just need to be careful when starting new events/stopping running ones.

As for reconstructing from content manager, this is way beyond the scope of server manager.
