### ISSUE TITLE
allow use of templates when determining final server name

### ISSUE THREAD

**Issue by cj123** [cj123/assetto-server-manager#488]
e.g. 

`{{ .serverName }} - {{ .eventName }}`

`{{ .eventName }} on my epic {{ .serverName }}`

`{{ .serverName }} | {{ .eventName }}`

**Comment by cheesegrits** [comment]
While you are doing that, any chance you can do the ...

"Hi, %s! Welcome to the %s server! %s %s Make this race count! %s\n"

... message as well?  Or at least move the "Make this race count!" into the default ServerJoinMessage?  Doesn't make much sense for non-race sessions.

**Comment by cj123** [comment]
Yeah I had considered this earlier. Will try to get it in with this one.
