### ISSUE TITLE
Driver's Status in Championship.

### ISSUE THREAD

**Issue by luismercury** [cj123/assetto-server-manager#494]
In a championship ... Can a driver verify his situation? Eg. Accept,Reject and Skins.

Could it be a query button here?
![image](https://user-images.githubusercontent.com/48275749/63938143-7caae800-ca3a-11e9-826c-a3ad8de79d71.png)

Could the answer be with these fields? Only "Create", "Name", "Car/Skins" and "Status". ( No Guid, No mail)
![image](https://user-images.githubusercontent.com/48275749/63937285-6d2a9f80-ca38-11e9-8316-1eacf68659af.png)

**Comment by cj123** [comment]
this is fixed by #533
