### ISSUE TITLE
nice priority

### ISSUE THREAD

**Issue by mike855** [cj123/assetto-server-manager#506]
Hello,

Do you think you can make possible for the server to start with nice ?
I have 7 servers hosted on the same dedicated server, and I want one to have higher priority because it is the championship server

**Comment by cj123** [comment]
Hi, you should be able to do this by making a script called `run.sh` in your assetto folder, next to acServer

```
#!/bin/bash

nice -n 19 ./acServer
```

and then setting 

```
steam:
  executable_path: run.sh
``` 

in the config

**Comment by mike855** [comment]
Oh I will take a look at that solution Thank you :)

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., sept. 5, 2019 à 14:51, Callum Jones<notifications@github.com> a écrit :   
Hi, you should be able to do this by making a script called run.sh in your assetto folder, next to acServer
#!/bin/bash

nice -n 19 ./acServer

and then setting
steam:
  executable_path: run.sh

in the config
