### ISSUE TITLE
Race Results json not public

### ISSUE THREAD

**Issue by port22** [cj123/assetto-server-manager#540]
The route `/results/download` should be public, but instead the requestor is redirected to the login page, which makes it impossible to use simresults.

I am using the Docker Image with traefik as loadbalancer with forced https-redirect, if that's important.

**Comment by port22** [comment]
The Championship Signup Page is also not public:
`/championship/8eaa10ac-2ca7-45e4-aaa8-cd6573148c92/sign-up`

is that intended or a configuration issue on my server?

**Comment by Hecrer** [comment]
This is probably due to your server not having open read access without an account. You can configure this on the ```Server -> Accounts``` page. 

![2019-10-07 10_28_47-Manage Accounts _ Big Whiskey](https://user-images.githubusercontent.com/34576650/66300501-5441c380-e8ed-11e9-970e-1a0e0cdf5988.png)

Thanks

**Comment by port22** [comment]
aaah found it, thanks!
I just startet to use it, so may be not my last issue, but I already find it's agreat piece of software and will definitely donate a bunch of beers when I basically got all working :-)
