### ISSUE TITLE
Championship error

### ISSUE THREAD

**Issue by xabipidal** [cj123/assetto-server-manager#577]
When I try to create a championship I get the error ... the page not work.... http error 500

![Screenshot_8](https://user-images.githubusercontent.com/56895771/67331834-8aeb2100-f51e-11e9-92cf-74d736c1761f.jpg)

**Comment by xabipidal** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/56895771/67331723-68590800-f51e-11e9-935c-8b33e9c34904.jpg)

**Comment by cj123** [comment]
fixed in #555
