### ISSUE TITLE
level=error msg="couldn't apply quick race" issue 

### ISSUE THREAD

**Issue by UncleRonald6681** [cj123/assetto-server-manager#597]
This is my first time using it and i followed the install tutorial and i ran my server and i keep getting an internal error 
You can ignore the Track problem because it only happens at that track. 

i included logs in the post

[server-manager.txt](https://github.com/cj123/assetto-server-manager/files/3776643/server-manager.txt)

**Comment by Hecrer** [comment]
Hi!

Looks to me like the path to your server executable is wrong in the config.yml, and server manager can't find it. Try using a relative path from the manager install location to the server instead of the full path. If that doesn't work send me your config.yml (remove any sensitive information first) and I'll see if I can spot the problem.

```error="exec: \"A:\\\\Steam\\\\steamapps\\\\common\\\\assettocorsa\\\\server\": file does not exist"```

**Comment by UncleRonald6681** [comment]
> 
> 
> Hi!
> 
> Looks to me like the path to your server executable is wrong in the config.yml, and server manager can't find it. Try using a relative path from the manager install location to the server instead of the full path. If that doesn't work send me your config.yml (remove any sensitive information first) and I'll see if I can spot the problem.
> 
> `error="exec: \"A:\\\\Steam\\\\steamapps\\\\common\\\\assettocorsa\\\\server\": file does not exist"`

Oh thank you! i had to add "acServer.exe" in the path. i thought i had to choose path of where it's located. 
So A:\Steam\steamapps\common\assettocorsa\server\acServer.exe worked

Before you close this forum.
Does this pink color on the track specify anything? 
http://prntscr.com/pp5zh2

**Comment by Hecrer** [comment]
That is to indicate the track is a mod, there should be a legend of what the colours mean by the dropdown! We're aware that it doesn't look quite right in dark mode, that should be fixed for the next release.

**Comment by UncleRonald6681** [comment]
> 
> 
> That is to indicate the track is a mod, there should be a legend of what the colours mean by the dropdown! We're aware that it doesn't look quite right in dark mode, that should be fixed for the next release.

Ah Thanks for the info!
You're awesome!
I will close the thread with this reply 😄
