### ISSUE TITLE
Editing entry list between sessions of a race weekend

### ISSUE THREAD

**Issue by TheStraing** [cj123/assetto-server-manager#598]
It would be nice to be able to make changes to the entry list between sessions of a race weekend in order to manually give some grid penalties to the drivers. (Or just have a penalty option on race weekends sessions).

**Comment by cj123** [comment]
You should be able to add penalties to drivers in the results of their sessions, and those will affect the starting grid of their next session. 

I suppose there might be a need for the "Manage EntryList" button on a session to be able to control penalties too?

**Comment by cj123** [comment]
Closing this due to the implemented penalty system for race weekend sessions (can be done in race weekend session results)
