### ISSUE TITLE
Account sharing

### ISSUE THREAD

**Issue by UncleRonald6681** [cj123/assetto-server-manager#606]
So if i make a new account and want my friend to be able to change stuff what link do i give him to access the site? i tried giving the url of the login screen but that didn't work for him

**Comment by Hecrer** [comment]
It should work exactly as you described, for example on one of our servers you would go to this link:

https://opengt3.assettocorsaservers.com/login

Although trying to access any page that requires you to be logged in will redirect you to a login page anyway.

Are you running the manager locally? Can he not access your manager at all?

**Comment by UncleRonald6681** [comment]
> 
> 
> It should work exactly as you described, for example on one of our servers you would go to this link:
> 
> https://opengt3.assettocorsaservers.com/login
> 
> Although trying to access any page that requires you to be logged in will redirect you to a login page anyway.
> 
> Are you running the manager locally? Can he not access your manager at all?
This is the link i have when i log in.
then I think it is local i guess how would i proceed to make it available for him?
http://127.0.0.1:8772/

**Comment by Hecrer** [comment]
Sorted out on Discord, needed to open ports and share public IP address, all working now!
