### ISSUE TITLE
Error when editing championships

### ISSUE THREAD

**Issue by TheStraing** [cj123/assetto-server-manager#642]
I get this error when I try to edit a championship.
When I try to edit the name in particular, it doesn't get saved.

I just get a error 500 in the browser.
This is the server's standard output:
panic(0xddfe60, 0xc0033c60c0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cj123/assetto-server-manager.(*ChampionshipManager).HandleCreateChampionship(0xc001784660, 0xc001e57d00, 0x8, 0xc002198fc0, 0xbed54e, 0x0)
        /home/cj/Projects/go/src/github.com/cj123/assetto-server-manager/championship_manager.go:241 +0x1d4e
github.com/cj123/assetto-server-manager.(*ChampionshipsHandler).submit(0xc001cd51f0, 0x14502c0, 0xc0023293b0, 0xc001e57d00)
        /home/cj/Projects/go/src/github.com/cj123/assetto-server-manager/championships_handler.go:67 +0x54
net/http.HandlerFunc.ServeHTTP(0xc001cf4af0, 0x14502c0, 0xc0023293b0, 0xc001e57d00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cj123/assetto-server-manager.(*AuditLogHandler).Middleware.func1(0x14502c0, 0xc0023293b0, 0xc001e57d00)
        /home/cj/Projects/go/src/github.com/cj123/assetto-server-manager/audit_log.go:70 +0x30b
net/http.HandlerFunc.ServeHTTP(0xc0036548c0, 0x14502c0, 0xc0023293b0, 0xc001e57d00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cj123/assetto-server-manager.(*AccountHandler).MustLoginMiddleware.func1(0x14502c0, 0xc0023293b0, 0xc001e57300)
        /home/cj/Projects/go/src/github.com/cj123/assetto-server-manager/accounts.go:159 +0x8ce
net/http.HandlerFunc.ServeHTTP(0xc00182e180, 0x14502c0, 0xc0023293b0, 0xc001e57300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc00157b0c0, 0x14502c0, 0xc0023293b0, 0xc001e57300)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/chain.go:31 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0033691a0, 0x14502c0, 0xc0023293b0, 0xc001e57300)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:425 +0x278
net/http.HandlerFunc.ServeHTTP(0xc001cd5300, 0x14502c0, 0xc0023293b0, 0xc001e57300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/getsentry/raven-go.Recoverer.func1(0x14502c0, 0xc0023293b0, 0xc001e57300)
        /home/cj/Projects/go/pkg/mod/github.com/getsentry/raven-go@v0.2.0/http.go:97 +0xbb
net/http.HandlerFunc.ServeHTTP(0xc00362d480, 0x14502c0, 0xc0023293b0, 0xc001e57300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi/middleware.Compress.func1.1(0x7fc2bd87b3e0, 0xc002329360, 0xc001e57300)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/compress.go:148 +0x1bf
net/http.HandlerFunc.ServeHTTP(0xc001805260, 0x7fc2bd87b3e0, 0xc002329360, 0xc001e57300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi/middleware.RealIP.func1(0x7fc2bd87b3e0, 0xc002329360, 0xc001e57300)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/realip.go:34 +0x99
net/http.HandlerFunc.ServeHTTP(0xc00362d4c0, 0x7fc2bd87b3e0, 0xc002329360, 0xc001e57300)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi/middleware.RequestID.func1(0x7fc2bd87b3e0, 0xc002329360, 0xc001e57100)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/middleware/request_id.go:72 +0x1dc
net/http.HandlerFunc.ServeHTTP(0xc00362d4e0, 0x7fc2bd87b3e0, 0xc002329360, 0xc001e57100)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0033691a0, 0x7fc2bd87b3e0, 0xc002329360, 0xc001e56c00)
        /home/cj/Projects/go/pkg/mod/github.com/go-chi/chi@v4.0.2+incompatible/mux.go:82 +0x2b2
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1(0x7fc2bd87b3e0, 0xc0023292c0, 0xc001e56c00)
        /home/cj/Projects/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/promhttp/instrument_server.go:196 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc001844ea0, 0x7fc2bd87b3e0, 0xc0023292c0, 0xc001e56c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /home/cj/Projects/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(0xc001845b90, 0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /home/cj/Projects/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc00184aa80, 0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /home/cj/Projects/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/promhttp/instrument_server.go:40 +0xbc
net/http.HandlerFunc.ServeHTTP(0xc00184ae40, 0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc0035d2540, 0x1451980, 0xc0022b8b60, 0xc001e56c00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc001930960, 0x14553c0, 0xc001144200)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2927 +0x38e

**Comment by cj123** [comment]
hi! what browser are you using? this might sound weird but I think this issue is caused by a javascript error...

**Comment by TheStraing** [comment]
Google chrome and the server manager versione is the latest one

Il Mar 12 Nov 2019, 15:51 Callum Jones <notifications@github.com> ha
scritto:

**Comment by cj123** [comment]
Does each class in the championship have cars selected for it? Could you give me some more detailed steps as to what you entered in the championship form so I can try to replicate it? Thanks

**Comment by TheStraing** [comment]
ok, I checked the selected cars and I noticed that for some reason a car
disappeared from the database... not from the content/cars folder.
I just rebuilt the index and now I do not get the error anymore.
But I can't understand why some cars have disappeared as well as some
tracks and events.

Il giorno mer 13 nov 2019 alle ore 15:13 Callum Jones <
notifications@github.com> ha scritto:
