### ISSUE TITLE
Stracker proxy plugin local port and plugin port

### ISSUE THREAD

**Issue by TheStraing** [cj123/assetto-server-manager#648]
Hi, 
when i set the stracker proxy plugin local port and plugin port on the stracker configuration page the values doesn't get written into the configuration file.
I wanted to chain kiss my rank to stracker but I cannot do that since stracker doesn't get configured in the right way.

![image](https://user-images.githubusercontent.com/16732179/68888217-ce4e3f00-071a-11ea-9083-40076240eb07.png)

**Comment by Hecrer** [comment]
Thanks for this! Fixed in the above pull request.

**Comment by ennimann** [comment]
Hi,
i have the same problem yet.
https://www.racedepartment.com/threads/ac-server-manager.165662/post-3085450
Regards
